# Generated by Django 3.1.1 on 2020-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollStaff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createstaff',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='createstaff',
            name='gender',
            field=models.CharField(default='not selected', max_length=11),
        ),
        migrations.AddField(
            model_name='createstaff',
            name='staffType',
            field=models.CharField(default='not selected', max_length=14),
        ),
        migrations.AlterField(
            model_name='createstaff',
            name='email',
            field=models.EmailField(default='not selected', max_length=250),
        ),
        migrations.AlterField(
            model_name='createstaff',
            name='name',
            field=models.CharField(default='not selected', max_length=70),
        ),
        migrations.AlterField(
            model_name='createstaff',
            name='password',
            field=models.CharField(default='not selected', max_length=100),
        ),
    ]
